### ISSUE TITLE
Secrets Management for Config Files

### ISSUE THREAD

**Issue by codingdiaz** [Kav91/nri-flex-concept#2]
This is awesome. I just got it working to ship CircleCI events and it took about 15 minutes to implement. 

I was wondering what your thoughts on key management were. i.e. the containerized version of this is great but, right now you have to bake in any keys in the config files. 

You could write an entrypoint script that uses sed to replace these from environment variables but, I was wondering if you had any ideas or if anyone else has asked for this. I am happy to contribute if you post the source.

**Comment by Kav91** [comment]
Thanks! I've got a new release that can substitute environment variables anywhere in the config files.
I'd like to have an option to have a config file completely encrypted too, but haven't thought it through yet.

Source is coming soon, just working with the right people to get it into the official NR github 😄

**Comment by Kav91** [comment]
@codingdiaz environment variable usage is available with the latest release now, so closing this one 😄
