### ISSUE TITLE
Sources for nri-flex

### ISSUE THREAD

**Issue by pholdings** [Kav91/nri-flex-concept#4]
Hi - this project looks super interesting, in particular for the Prometheus exporter integration. 

In the project README, it says, "New Relic has open-sourced this integration to enable monitoring of various technologies.". However, I don't see the sources or the build toolchain for nri-flex. Are these available, or will they be made available? 

Thanks!

**Comment by Kav91** [comment]
@pholdings apologies for the delayed reply, we should be making it available officially under the newrelic github. Actively working with the team to set the appropriate licensing and sort this out as there has been a lot of usage of this project now. 
Timing aiming for around September.

**Comment by Kav91** [comment]
@pholdings Flex has now moved :) https://github.com/newrelic/nri-flex/
