### ISSUE TITLE
Example dashboards and NRQL

### ISSUE THREAD

**Issue by meringu** [Kav91/nri-flex-concept#5]
Hi,

I've got flex set up scaping a bunch of Prometheus metrics endpoints.

I'm struggling to set up dashboards in Insights based on the data from flex.

I would be interested to see some example dashboards for common Prometheus metric types.

In particular, would like to see example NRQL for histograms and summaries as these are the ones I am struggling with the most.

Thanks

**Comment by Kav91** [comment]
hey, we are thinking of a way to dynamically create dashboards for any of these event types, so we're spiking a few ideas even if we can do like a starter template of some sort with some pre-populated queries and visualisations so you're not starting from scratch.
